// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RepeatedPojo.proto

package protobuf.repeatedPojo;

public final class RepeatedPojo {
  private RepeatedPojo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PojoMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.repeatedPojo.PojoMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string reqId = 1;</code>
     */
    java.lang.String getReqId();
    /**
     * <code>string reqId = 1;</code>
     */
    com.google.protobuf.ByteString
        getReqIdBytes();

    /**
     * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
     */
    java.util.List<protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry> 
        getParamPojoList();
    /**
     * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
     */
    protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry getParamPojo(int index);
    /**
     * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
     */
    int getParamPojoCount();
    /**
     * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
     */
    java.util.List<? extends protobuf.repeatedPojo.RepeatedPojo.MapFieldEntryOrBuilder> 
        getParamPojoOrBuilderList();
    /**
     * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
     */
    protobuf.repeatedPojo.RepeatedPojo.MapFieldEntryOrBuilder getParamPojoOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.repeatedPojo.PojoMap}
   */
  public  static final class PojoMap extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.repeatedPojo.PojoMap)
      PojoMapOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PojoMap.newBuilder() to construct.
    private PojoMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PojoMap() {
      reqId_ = "";
      paramPojo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PojoMap(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              reqId_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                paramPojo_ = new java.util.ArrayList<protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry>();
                mutable_bitField0_ |= 0x00000002;
              }
              paramPojo_.add(
                  input.readMessage(protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          paramPojo_ = java.util.Collections.unmodifiableList(paramPojo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.repeatedPojo.RepeatedPojo.internal_static_protobuf_repeatedPojo_PojoMap_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.repeatedPojo.RepeatedPojo.internal_static_protobuf_repeatedPojo_PojoMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.repeatedPojo.RepeatedPojo.PojoMap.class, protobuf.repeatedPojo.RepeatedPojo.PojoMap.Builder.class);
    }

    private int bitField0_;
    public static final int REQID_FIELD_NUMBER = 1;
    private volatile java.lang.Object reqId_;
    /**
     * <code>string reqId = 1;</code>
     */
    public java.lang.String getReqId() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqId_ = s;
        return s;
      }
    }
    /**
     * <code>string reqId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReqIdBytes() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMPOJO_FIELD_NUMBER = 2;
    private java.util.List<protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry> paramPojo_;
    /**
     * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
     */
    public java.util.List<protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry> getParamPojoList() {
      return paramPojo_;
    }
    /**
     * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
     */
    public java.util.List<? extends protobuf.repeatedPojo.RepeatedPojo.MapFieldEntryOrBuilder> 
        getParamPojoOrBuilderList() {
      return paramPojo_;
    }
    /**
     * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
     */
    public int getParamPojoCount() {
      return paramPojo_.size();
    }
    /**
     * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
     */
    public protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry getParamPojo(int index) {
      return paramPojo_.get(index);
    }
    /**
     * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
     */
    public protobuf.repeatedPojo.RepeatedPojo.MapFieldEntryOrBuilder getParamPojoOrBuilder(
        int index) {
      return paramPojo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getReqIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reqId_);
      }
      for (int i = 0; i < paramPojo_.size(); i++) {
        output.writeMessage(2, paramPojo_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReqIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reqId_);
      }
      for (int i = 0; i < paramPojo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, paramPojo_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.repeatedPojo.RepeatedPojo.PojoMap)) {
        return super.equals(obj);
      }
      protobuf.repeatedPojo.RepeatedPojo.PojoMap other = (protobuf.repeatedPojo.RepeatedPojo.PojoMap) obj;

      boolean result = true;
      result = result && getReqId()
          .equals(other.getReqId());
      result = result && getParamPojoList()
          .equals(other.getParamPojoList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQID_FIELD_NUMBER;
      hash = (53 * hash) + getReqId().hashCode();
      if (getParamPojoCount() > 0) {
        hash = (37 * hash) + PARAMPOJO_FIELD_NUMBER;
        hash = (53 * hash) + getParamPojoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.repeatedPojo.RepeatedPojo.PojoMap parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.PojoMap parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.PojoMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.PojoMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.PojoMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.PojoMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.PojoMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.PojoMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.PojoMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.PojoMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.PojoMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.PojoMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.repeatedPojo.RepeatedPojo.PojoMap prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.repeatedPojo.PojoMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.repeatedPojo.PojoMap)
        protobuf.repeatedPojo.RepeatedPojo.PojoMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.repeatedPojo.RepeatedPojo.internal_static_protobuf_repeatedPojo_PojoMap_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.repeatedPojo.RepeatedPojo.internal_static_protobuf_repeatedPojo_PojoMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.repeatedPojo.RepeatedPojo.PojoMap.class, protobuf.repeatedPojo.RepeatedPojo.PojoMap.Builder.class);
      }

      // Construct using protobuf.repeatedPojo.RepeatedPojo.PojoMap.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getParamPojoFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        reqId_ = "";

        if (paramPojoBuilder_ == null) {
          paramPojo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          paramPojoBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.repeatedPojo.RepeatedPojo.internal_static_protobuf_repeatedPojo_PojoMap_descriptor;
      }

      public protobuf.repeatedPojo.RepeatedPojo.PojoMap getDefaultInstanceForType() {
        return protobuf.repeatedPojo.RepeatedPojo.PojoMap.getDefaultInstance();
      }

      public protobuf.repeatedPojo.RepeatedPojo.PojoMap build() {
        protobuf.repeatedPojo.RepeatedPojo.PojoMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.repeatedPojo.RepeatedPojo.PojoMap buildPartial() {
        protobuf.repeatedPojo.RepeatedPojo.PojoMap result = new protobuf.repeatedPojo.RepeatedPojo.PojoMap(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.reqId_ = reqId_;
        if (paramPojoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            paramPojo_ = java.util.Collections.unmodifiableList(paramPojo_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.paramPojo_ = paramPojo_;
        } else {
          result.paramPojo_ = paramPojoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.repeatedPojo.RepeatedPojo.PojoMap) {
          return mergeFrom((protobuf.repeatedPojo.RepeatedPojo.PojoMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.repeatedPojo.RepeatedPojo.PojoMap other) {
        if (other == protobuf.repeatedPojo.RepeatedPojo.PojoMap.getDefaultInstance()) return this;
        if (!other.getReqId().isEmpty()) {
          reqId_ = other.reqId_;
          onChanged();
        }
        if (paramPojoBuilder_ == null) {
          if (!other.paramPojo_.isEmpty()) {
            if (paramPojo_.isEmpty()) {
              paramPojo_ = other.paramPojo_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureParamPojoIsMutable();
              paramPojo_.addAll(other.paramPojo_);
            }
            onChanged();
          }
        } else {
          if (!other.paramPojo_.isEmpty()) {
            if (paramPojoBuilder_.isEmpty()) {
              paramPojoBuilder_.dispose();
              paramPojoBuilder_ = null;
              paramPojo_ = other.paramPojo_;
              bitField0_ = (bitField0_ & ~0x00000002);
              paramPojoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getParamPojoFieldBuilder() : null;
            } else {
              paramPojoBuilder_.addAllMessages(other.paramPojo_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.repeatedPojo.RepeatedPojo.PojoMap parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.repeatedPojo.RepeatedPojo.PojoMap) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object reqId_ = "";
      /**
       * <code>string reqId = 1;</code>
       */
      public java.lang.String getReqId() {
        java.lang.Object ref = reqId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reqId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reqId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReqIdBytes() {
        java.lang.Object ref = reqId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reqId = 1;</code>
       */
      public Builder setReqId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reqId = 1;</code>
       */
      public Builder clearReqId() {
        
        reqId_ = getDefaultInstance().getReqId();
        onChanged();
        return this;
      }
      /**
       * <code>string reqId = 1;</code>
       */
      public Builder setReqIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry> paramPojo_ =
        java.util.Collections.emptyList();
      private void ensureParamPojoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          paramPojo_ = new java.util.ArrayList<protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry>(paramPojo_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry, protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.Builder, protobuf.repeatedPojo.RepeatedPojo.MapFieldEntryOrBuilder> paramPojoBuilder_;

      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public java.util.List<protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry> getParamPojoList() {
        if (paramPojoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(paramPojo_);
        } else {
          return paramPojoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public int getParamPojoCount() {
        if (paramPojoBuilder_ == null) {
          return paramPojo_.size();
        } else {
          return paramPojoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry getParamPojo(int index) {
        if (paramPojoBuilder_ == null) {
          return paramPojo_.get(index);
        } else {
          return paramPojoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public Builder setParamPojo(
          int index, protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry value) {
        if (paramPojoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamPojoIsMutable();
          paramPojo_.set(index, value);
          onChanged();
        } else {
          paramPojoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public Builder setParamPojo(
          int index, protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.Builder builderForValue) {
        if (paramPojoBuilder_ == null) {
          ensureParamPojoIsMutable();
          paramPojo_.set(index, builderForValue.build());
          onChanged();
        } else {
          paramPojoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public Builder addParamPojo(protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry value) {
        if (paramPojoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamPojoIsMutable();
          paramPojo_.add(value);
          onChanged();
        } else {
          paramPojoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public Builder addParamPojo(
          int index, protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry value) {
        if (paramPojoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureParamPojoIsMutable();
          paramPojo_.add(index, value);
          onChanged();
        } else {
          paramPojoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public Builder addParamPojo(
          protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.Builder builderForValue) {
        if (paramPojoBuilder_ == null) {
          ensureParamPojoIsMutable();
          paramPojo_.add(builderForValue.build());
          onChanged();
        } else {
          paramPojoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public Builder addParamPojo(
          int index, protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.Builder builderForValue) {
        if (paramPojoBuilder_ == null) {
          ensureParamPojoIsMutable();
          paramPojo_.add(index, builderForValue.build());
          onChanged();
        } else {
          paramPojoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public Builder addAllParamPojo(
          java.lang.Iterable<? extends protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry> values) {
        if (paramPojoBuilder_ == null) {
          ensureParamPojoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, paramPojo_);
          onChanged();
        } else {
          paramPojoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public Builder clearParamPojo() {
        if (paramPojoBuilder_ == null) {
          paramPojo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          paramPojoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public Builder removeParamPojo(int index) {
        if (paramPojoBuilder_ == null) {
          ensureParamPojoIsMutable();
          paramPojo_.remove(index);
          onChanged();
        } else {
          paramPojoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.Builder getParamPojoBuilder(
          int index) {
        return getParamPojoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public protobuf.repeatedPojo.RepeatedPojo.MapFieldEntryOrBuilder getParamPojoOrBuilder(
          int index) {
        if (paramPojoBuilder_ == null) {
          return paramPojo_.get(index);  } else {
          return paramPojoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public java.util.List<? extends protobuf.repeatedPojo.RepeatedPojo.MapFieldEntryOrBuilder> 
           getParamPojoOrBuilderList() {
        if (paramPojoBuilder_ != null) {
          return paramPojoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(paramPojo_);
        }
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.Builder addParamPojoBuilder() {
        return getParamPojoFieldBuilder().addBuilder(
            protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.Builder addParamPojoBuilder(
          int index) {
        return getParamPojoFieldBuilder().addBuilder(
            index, protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.repeatedPojo.MapFieldEntry paramPojo = 2;</code>
       */
      public java.util.List<protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.Builder> 
           getParamPojoBuilderList() {
        return getParamPojoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry, protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.Builder, protobuf.repeatedPojo.RepeatedPojo.MapFieldEntryOrBuilder> 
          getParamPojoFieldBuilder() {
        if (paramPojoBuilder_ == null) {
          paramPojoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry, protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.Builder, protobuf.repeatedPojo.RepeatedPojo.MapFieldEntryOrBuilder>(
                  paramPojo_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          paramPojo_ = null;
        }
        return paramPojoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.repeatedPojo.PojoMap)
    }

    // @@protoc_insertion_point(class_scope:protobuf.repeatedPojo.PojoMap)
    private static final protobuf.repeatedPojo.RepeatedPojo.PojoMap DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.repeatedPojo.RepeatedPojo.PojoMap();
    }

    public static protobuf.repeatedPojo.RepeatedPojo.PojoMap getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PojoMap>
        PARSER = new com.google.protobuf.AbstractParser<PojoMap>() {
      public PojoMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PojoMap(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PojoMap> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PojoMap> getParserForType() {
      return PARSER;
    }

    public protobuf.repeatedPojo.RepeatedPojo.PojoMap getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MapFieldEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.repeatedPojo.MapFieldEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>string value = 2;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code protobuf.repeatedPojo.MapFieldEntry}
   */
  public  static final class MapFieldEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.repeatedPojo.MapFieldEntry)
      MapFieldEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MapFieldEntry.newBuilder() to construct.
    private MapFieldEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MapFieldEntry() {
      key_ = "";
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MapFieldEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.repeatedPojo.RepeatedPojo.internal_static_protobuf_repeatedPojo_MapFieldEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.repeatedPojo.RepeatedPojo.internal_static_protobuf_repeatedPojo_MapFieldEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.class, protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.Builder.class);
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /**
     * <code>string value = 2;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry)) {
        return super.equals(obj);
      }
      protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry other = (protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry) obj;

      boolean result = true;
      result = result && getKey()
          .equals(other.getKey());
      result = result && getValue()
          .equals(other.getValue());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.repeatedPojo.MapFieldEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.repeatedPojo.MapFieldEntry)
        protobuf.repeatedPojo.RepeatedPojo.MapFieldEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.repeatedPojo.RepeatedPojo.internal_static_protobuf_repeatedPojo_MapFieldEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.repeatedPojo.RepeatedPojo.internal_static_protobuf_repeatedPojo_MapFieldEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.class, protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.Builder.class);
      }

      // Construct using protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        key_ = "";

        value_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.repeatedPojo.RepeatedPojo.internal_static_protobuf_repeatedPojo_MapFieldEntry_descriptor;
      }

      public protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry getDefaultInstanceForType() {
        return protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.getDefaultInstance();
      }

      public protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry build() {
        protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry buildPartial() {
        protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry result = new protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry(this);
        result.key_ = key_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry) {
          return mergeFrom((protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry other) {
        if (other == protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 2;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.repeatedPojo.MapFieldEntry)
    }

    // @@protoc_insertion_point(class_scope:protobuf.repeatedPojo.MapFieldEntry)
    private static final protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry();
    }

    public static protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MapFieldEntry>
        PARSER = new com.google.protobuf.AbstractParser<MapFieldEntry>() {
      public MapFieldEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MapFieldEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MapFieldEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MapFieldEntry> getParserForType() {
      return PARSER;
    }

    public protobuf.repeatedPojo.RepeatedPojo.MapFieldEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_repeatedPojo_PojoMap_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_repeatedPojo_PojoMap_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_repeatedPojo_MapFieldEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_repeatedPojo_MapFieldEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022RepeatedPojo.proto\022\025protobuf.repeatedP" +
      "ojo\"Q\n\007PojoMap\022\r\n\005reqId\030\001 \001(\t\0227\n\tparamPo" +
      "jo\030\002 \003(\0132$.protobuf.repeatedPojo.MapFiel" +
      "dEntry\"+\n\rMapFieldEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\tB\002H\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_repeatedPojo_PojoMap_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_repeatedPojo_PojoMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_repeatedPojo_PojoMap_descriptor,
        new java.lang.String[] { "ReqId", "ParamPojo", });
    internal_static_protobuf_repeatedPojo_MapFieldEntry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_repeatedPojo_MapFieldEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_repeatedPojo_MapFieldEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
